language: python
python:
  - "3.6"
sudo: enabled
install:
  - make setup-travis
  - pip install codecov
script:
  - make test
  - make check-pep8
after_success:
  - codecov
branches:
  only:
    - master

